boostcampwm2023/web05-AlgoITNi

.github/workflows/front-release-deploy.yml
yml 레포지토리를 받아오고 의존성 설치하는 로직 추가
working directory를 계속해서 찾지 못하는 오류가 있었는데, 이는 actions 도커에 github 코드를 주지 않았기 때문이다...
checkout 하는 부분을 추가해주었고, 의존성 설치도 하지않았었는데, 그 부분을 해주었다.
=> [FE] fix: yml 레포지토리를 받아오고 의존성 설치하는 로직 추가

frontEnd/.githooks/pre-commit, frontEnd/package-lock.json, frontEnd/package.json, setup.sh
- 프로젝트 루트에서 ./setup 명령어를 통해 githooks 경로를 설정 가능
- 하나의 레포지토리에서 husky를 적용하기에 어려움이 있었음
- husky의 경우 프로젝트 루트에 있는 `.git`과 동일한 위치에 존재해야 문제없이 사용할 수 있었음
- 이를 해결하기 위해 `.githooks`라는 기능을 이용
- 별도의 모듈 설치가 필요없으며 복잡한 설정이 필요 없이 `it config core.hooksPath .{githooks 디렉토리 위치}`만 설정해주면 됨
- 이 과정에서 작업의 효율성을 위해 쉘 스크립트로 설정할 수 있도록 쉘 스크립트를 작성
```bash
#!/bin/bash
PS3='개발 환경을 선택해주세요: '
options=("front-end" "back-end" "Quit")
select opt in "${options[@]}"
do
case $opt in
"front-end")
echo -e "\n\033[32mfront-end\033[0m를 선택하셨습니다."
git config core.hooksPath ./frontEnd/.githooks
break
;;
"back-end")
echo -e "\n\033[32mback-end\033[0m를 선택하셨습니다."
git config core.hooksPath ./backEnd/.githooks
break
;;
"Quit")
break
;;
*) echo "잘못된 선택입니다. 1-3 사이의 번호를 선택해주세요.";;
esac
done
echo -e "현재 githooks 경로: \033[32m$(git config --get …
```
=> [FE/BE] feat: FE githooks 및 setup 쉘 스크립트 작성

frontEnd/.eslintrc.cjs
- eslint에서 tsconfig 파일을 찾지 못하는 문제를 해결하기 위해 .eslintrc.cjs parserOptions에 tsconfigRootDir: __dirname 추가
```diff
parserOptions: {
(...)
+   tsconfigRootDir: __dirname
}
```
=> [FE] fix: eslint tsconfigRootDir 추가

frontEnd/.eslintrc.cjs, frontEnd/package-lock.json, frontEnd/package.json, frontEnd/src/constants/socketEvents.ts, frontEnd/src/constants/urls.ts, frontEnd/src/main.tsx, frontEnd/src/pages/Room.tsx, frontEnd/src/services/RTC.ts, frontEnd/src/services/Socket.ts, frontEnd/src/stores/StreamModel.ts, frontEnd/src/utils/Observer.ts
프론트엔드 WebRTC 구현 
WebRTC를 mesh방식의 P2P로 구현
WebRTC 로직
**`사용자 A`, `사용자 B`** 가 webRTC로 통신하는 상황
1. **`사용자 A`**, 방에 입장
2. **`사용자 B`**, 방에 입장시 welcome이벤트 발생, 서버로 전달
3.  **`사용자 A`** , welcome 이벤트수신
4. **`사용자 A`**, offer생성 + setLocalDescription을 통해 자신의 offer세팅
5. **`사용자 A`**, offer 이벤트발생, 서버로 전달
6. **`사용자 B`** , offer 이벤트 수신, offer를 setRemoteDescription으로 세팅, answer객체 생성 후 setLocalDescription을 통해 answer를 세팅
7. **`사용자 B`**, answer 이벤트 발생, 서버로 전달
8. **`사용자 A`**, answer 이벤트 수신,setRemoteDescription으로 세팅
9. localDescripton과 remoteDescription이 모두 설정되어 ICECandidates를 수집하기 시작함 ⇒ **`icecandidate 이벤트가 발생`**
10. rtc connection객체에 등록된 icecandidate 이벤트핸들러로 등록된 함수에서 ice 이벤트 발생, 서버로 전송, data.candiate데이터 전송
11. 서버에서 방의 모든 사용자에게 data.candidate를 브로드캐스팅
12. 사용자 각각은 data.candidate를 addIceCandidate함수로 추가함
13. rtc …
=> [FE] feat: 프론트엔드 WebRTC 구현 

frontEnd/package-lock.json, frontEnd/package.json, frontEnd/src/pages/Room.tsx, frontEnd/src/services/RTC.ts, frontEnd/src/services/Socket.ts
- WebRTC에서 remote description이 등록되기 전에 ice candidate가 제대로 교환되지 않던 문제 해결
- ice candidate 수신 이벤트 핸들러에서 remote description의 존재 여부를 확인하는 if문 제거
=> [FE] fix: WebRTC에서 remote description이 등록되기 전에 ice candidate가 제대로 교환되지 않던 문제 해결

.github/workflows/front-ci.yml, .github/workflows/front-release-deploy.yml
프론트엔드 배포방식을 object storage를 사용한 방식에서 s3와 cloudFront를 사용한 방식으로 변경했다.
Object Storage는 커스텀 도메인이 붙지 않기 때문이다...
또한 기존에 aws cli명령어를 통해서 Object Storage에 접근하고 있었기 때문에 가장 비슷한 S3버킷을 사용한 방식으로 바꾸어주었다.
S3 버킷의 모든 데이터를 퍼블릭으로 설정하거나, 웹사이트 호스팅을 하는 형태가 아니라 CloudFront 배포를 통해서만 리소스에 접근 할 수 있게 했다.
main, FE/release에 push되는 경우에만 deploy되게 했고, 다른 경우에는 CI만 하도록 yml을 두개 작성했다.
dev에 머지 될때마다 새롭게 배포되는것보다는 CI만 시키는 것이 합리적이라는 판단이다.
=> [FE] config: ncp object storage에서 s3, cloudfront를 사용한 배포로 변경

frontEnd/.gitignore, frontEnd/src/hooks/useRoom.ts, frontEnd/src/pages/Room.tsx
- WebRTC 코드 useRoom으로 변경 및 .env 설정
- 사용자들의 스트림 정보를 관리하는 과정에서 새로운 사용자가 들어오는 등의 경우 해당 스트림을 업데이트 하면서 재렌더링을 해야했음
- 이를 해결하기 위해 useRoom 훅으로 변환하고 해당 훅 안에서 streamList를 관리할 수 있도록 함
- 해당 state를 반환하여 컴포넌트에서 사용할 수 있도록 했으며 state가 변화함에 따라 재렌더링이 일어날 수 있도록 구성
```ts
const useRoom = (roomId: string) => {
const [streamList, setStreamList] = useState<{ id: string; stream: MediaStream }[]>([]);
```
=> [FE] refactor: WebRTC 코드 useRoom으로 변경 및 .env 설정

backEnd/.githooks/pre-commit, backEnd/api/package-lock.json, backEnd/api/package.json, backEnd/api/src/app.controller.spec.ts, backEnd/api/src/app.controller.ts, backEnd/api/src/app.module.ts, backEnd/api/src/common/logger/winstonLogger.service.ts, backEnd/api/src/main.ts, backEnd/api/src/users/users.controller.spec.ts, backEnd/api/src/users/users.controller.ts, backEnd/api/src/users/users.module.ts, backEnd/running/package-lock.json, backEnd/running/package.json, backEnd/running/src/app.module.ts, backEnd/running/src/common/logger/winstonLogger.service.ts, backEnd/running/src/main.ts, backEnd/signaling/package-lock.json, backEnd/signaling/package.json, backEnd/signaling/src/app.module.ts, backEnd/signaling/src/app.service.ts, backEnd/signaling/src/common/logger/winstonLogger.service.ts, backEnd/signaling/src/main.ts, backEnd/signaling/src/webRTC/web-rtc.gateway.ts
- 백엔드 기본 세팅 추가
lint-staged 적용 후 commit 시 콘솔의 결과
winston logger만 사용할 때랑 nest LoggerService를 구현한 Winston Logger는 로그 레벨에서 약간의 차이를 보임
``` javascript
// LoggerService Interface
export interface LoggerService {
/**
* Write a 'log' level log.
*/
log(message: any, ...optionalParams: any[]): any;
/**
* Write an 'error' level log.
*/
error(message: any, ...optionalParams: any[]): any;
/**
* Write a 'warn' level log.
*/
warn(message: any, ...optionalParams: any[]): any;
/**
* Write a 'debug' level log.
*/
debug?(message: any, ...optionalParams: any[]): any;
/**
* Write a 'verbose' level log.
*/
verbose?(message: any, ...optionalParams: any[]): any;
/**
* Write a 'fatal' level log.
*/
fatal?(message: any, ...optionalParams: any[]): any;
/**
* Set log levels.
* @param levels log levels
*/ …
```
=> [BE] feat: 백엔드 로거, 린트 설정 추가

frontEnd/.eslintrc.cjs, frontEnd/package-lock.json, frontEnd/package.json, frontEnd/src/components/Editor.tsx, frontEnd/src/pages/Room.tsx, frontEnd/src/styles/editor.css, frontEnd/src/styles/index.css
- CRDT (yjs 라이브러리) 적용
- close #54 
- 에디터에서는 `textarea` 태그를 사용중이기 때문에 부분적인 하이라이팅이 불가능
- `highlight.js` 모듈을 설치하고 `<pre><code></code></pre>`를 이용해 라이라이트 된 코드를 보여줄 수 있도록 구성
- 단, 입력은 여전히 textarea를 사용하고 사용자에게 보이는 부분이 `<pre>` 부분이 되어야 함
- 이를 위해 `position: absolute`를 이용해 textarea와 pre가 겹치도록 한 뒤, textarea의 z-index를 pre보다 높게 설정하여 textarea가 클릭되도록 구성
- 둘의 자간, 행간 너비를 동일하게 하여 완전히 겹쳐질 수 있도록 구성
- 결과적으로 실제 텍스트는 textarea에 있으며, 사용자에게 보이는 부분은 pre를 이용한 부분이 될 수 있도록 함
- `<code>`안의 내용을 `dangerouslySetInnerHTML`를 사용하여 설정하기 때문에 XSS에 대한 대비가 필요했음
- 이를 위해 `dompurify`를 추가하여 텍스트를 검증할 수 있도록 구성
- 또한, textarea와 pre의 스크롤바를 동기화 시켜야 했음
- 두 요소에 `onscroll`이벤트를 설정하여 같은 비율로 스크롤 될 수 있도록 구성
=> [FE] feat: CRDT (yjs 라이브러리) 적용

backEnd/center/.eslintrc.js, backEnd/center/.gitignore, backEnd/center/.prettierrc, backEnd/center/Dockerfile, backEnd/center/README.md, backEnd/center/nest-cli.json, backEnd/center/package-lock.json, backEnd/center/package.json, backEnd/center/src/app.controller.spec.ts, backEnd/center/src/app.controller.ts, backEnd/center/src/app.module.ts, backEnd/center/src/app.service.ts, backEnd/center/src/common/exception/exception.filter.ts, backEnd/center/src/connections/connections.controller.spec.ts, backEnd/center/src/connections/connections.controller.ts, backEnd/center/src/connections/connections.module.ts, backEnd/center/src/connections/connections.service.spec.ts, backEnd/center/src/connections/connections.service.ts, backEnd/center/src/connections/dto/register-signaling-socket.dto.ts, backEnd/center/src/connections/dto/return-connections.dto copy.ts, backEnd/center/src/connections/dto/signaling-connections.dto.ts, backEnd/center/src/main.ts, backEnd/center/test/app.e2e-spec.ts, backEnd/center/test/jest-e2e.json, backEnd/center/tsconfig.build.json, backEnd/center/tsconfig.json
- 다중 소켓 서버를 위해 중앙 서버 구현
* 확장성을 고려하여 Redis에 연결하여 소켓과 룸 정보를 저장할지 고민이 많았음
* 하지만 Redis를 사용하는 것보다 메모리 방식이 좀 더 빠를것 같다고 생각했기에 메모리 방식 구현
=> [BE] feat: 다중 소켓 서버를 위한 중앙 서버로직 구현

.github/workflows/back-api-cd.yml, backEnd/api/Dockerfile, backEnd/api/src/common/exception/exception.filter.ts, backEnd/api/src/common/interceptor/timeout.intercetor.ts, backEnd/api/src/redis/redis.service.ts, backEnd/api/src/run/run.controller.ts, backEnd/api/src/run/run.service.ts, backEnd/running/package-lock.json, backEnd/running/package.json, backEnd/running/src/codes/codes.service.ts, backEnd/running/src/common/decorator/timeout.decorator.ts, backEnd/running/src/common/exception/exception.filter.ts, backEnd/running/src/common/exception/exception.ts, backEnd/running/src/common/interceptor/timeout.interceptor.ts, backEnd/running/src/mq/dto/response-codeblock.dto.ts, backEnd/running/src/mq/mq.consumer.ts, backEnd/running/src/redis/redis.service.ts
issue #36 
코드 실행 기능 중 실행에 5초이상 걸리는 코드는 중지하는 기능 구현
- timeout interceptor 수정
기존은 timeout 시 http 요청 주기 종료되지 않고 슬랙 알림만 보내짐
dev 환경에서는 슬랙 알림이 보내지지 않고, 타임아웃시 http 수명주기를 종료하게 Timeout Exception을 throw함
- 코드 실행 5초 타임아웃 설정 
파이썬 코드는 자식 프로세스를 생성해서 실행하게 됨.
이때 promise resolve, reject, setTimeout을 이용해서 5초이내에 원래 자식프로세스 실행이 끝나지 않으면 자식프로세스에 `SIGINT` 신호를 보내 종료시킴
- 코드 실행 요청에 대한 응답 형식 통일
코드 실행 요청 api를 구현 방식에 따라 v1, v2로 구성하였는데
실행 방식에 따라서 응답 형식이 다른 문제가 있었음.
api서버와 running 서버에 동일한 DTO를 추가해주어 응답형식을 두 버전이 동일하게 추가해주었음.
=> [BE]: feature 코드 실행 타임아웃 설정

frontEnd/src/components/room/EditorSection.tsx, frontEnd/src/components/room/editor/Editor.tsx, frontEnd/src/components/room/editor/LoadButton.tsx, frontEnd/src/components/room/modal/LoginModal.tsx, frontEnd/src/components/room/modal/SaveModal.tsx, frontEnd/src/pages/Room.tsx
- PR에 관한 간단한 설명
로그인 버튼을 누를때, 해당 코드를 localStorage에 잠시 저장한 후, 리다이렉션이 되면 room에서 localStorage의 값을 검사하고, 값이 있다면 setting창을 보여주지 않고 바로 방에 재참여시키도록 했다.
참여가 완료되면 코드를 복구하고, localStorage를 비우는식으로 구현했다.
=> [FE] fix: 로그인에서 발생하는 이슈 해결

frontEnd/package-lock.json, frontEnd/package.json, frontEnd/src/components/room/editor/LoadButton.tsx, frontEnd/src/components/room/modal/SaveModal.tsx, frontEnd/src/components/room/modal/tests/SaveModal.test.tsx, frontEnd/src/configs/reactQueryClient.ts, frontEnd/src/constants/queryKeys.ts, frontEnd/src/main.tsx, frontEnd/src/pages/tests/Room.test.tsx, frontEnd/src/utils/authFailCallback.ts
react-query 적용
클라이언트에서 서버 데이터를 저장하여 서버로 가는 api요청을 줄이고, 사용자가 빠르게 화면을 볼 수 있도록 할 수 있다.
우리 서비스의 경우, modal이 뜨기까지 사용자가 기다려야하는 문제가 있는데, react-query를 사용하면 이부분에 드는 시간을 최소화시킬 수 있다.
또한, 사용자가 자신의 코드를 업데이트 할때에만 stale처리를 해주면되므로, 관리도 간편하다.
리액트 쿼리에서 공통 에러처리를 queryClient를 통해 할 수 있는데, 이부분에서 modal을띄워야하는 문제가 있었다.
일단은 failed Callback을 적용시키는 식으로 공통코드를 처리했다.
```typescript
import { isAxiosError } from 'axios';
export default function createAuthFailCallback(callback: () => void) {
return (err: Error) => {
if (isAxiosError(err) && err.response && (err.response.status === 401 || err.response.status === 403)) {
callback();
}
};
}
```
이런식으로 처리해주었다.
```typescript
...
const { data, isError, error, refetch } = useQuery({
queryKey: [QUERY_KEYS.LOAD_CODES],
queryFn: getUserCodes,
enabled: false,
});
const errorCallback = …
```
=> [FE] feat: react-query 적용

frontEnd/src/apis/putUserCode.ts, frontEnd/src/components/common/Button.tsx, frontEnd/src/components/room/editor/SaveButton.tsx, frontEnd/src/components/room/modal/CodeListModal.tsx, frontEnd/src/components/room/modal/SaveChoiceModal.tsx, frontEnd/src/stores/useModifyState.ts, frontEnd/tailwind.config.js
- PR에 관한 간단한 설명
코드 수정을 어떻게 구현할 것인가?
=> 불러오기를 한 후에는 수정할 것인지, 새로 파일을 저장할 것인지 묻는 식으로 해결
=> [FE] feat: 코드 수정하기 

.github/workflows/back-api-cd.yml, backEnd/api/.gitignore, backEnd/api/src/auth/auth.controller.ts, backEnd/api/src/auth/auth.service.ts, backEnd/api/src/auth/google/google.service.ts, backEnd/api/src/main.ts
-  개발용 토큰 발급을 위한 api입니다.
기존 env 파일 생성 방식으로는 새로운 환경변수 값이 생길 때 마다 yml, github secret 등록을 해주어야했고,
cd 파일이 너무너무 길어지는 불편함이 있었습니다.
env 파일 생성을 간편하게 하기 위해서 env 파일을 통채로 github secret에 등록하고 한 번에 읽어와 .env 파일을 만드는 방법으로 변경했습니다.
```
script: |
cd /root
echo "${{secrets.API_ENV}}" > .env
bash deploy.sh >> /dev/deploy.log 2>&1
```
script 가 간결해졌습니다!
로컬 환경에서 사용한 환경변수는 .env에 github secret에 넣어줄 배포환경의 환경변수는 .prod.env로 기록하며 별도로 관리하려고 합니다.
=> [BE] feature: 개발용 토큰 발급

backEnd/api/src/auth/google/google.service.ts, backEnd/api/src/codes/codes.controller.ts, backEnd/api/src/codes/codes.module.ts, backEnd/api/src/codes/dto/getCode.dto.ts, backEnd/api/src/codes/dto/saveCode.dto.ts, backEnd/api/src/codes/pipes/saveCode.pipe.ts, backEnd/api/src/codes/schemas/code.schemas.ts, backEnd/api/src/common/exception/exception.ts, backEnd/api/src/common/type.ts, backEnd/api/src/common/utils.ts, backEnd/api/src/mq/mq.service.ts, backEnd/api/src/run/dto/request-codeblock.dto.ts, backEnd/api/src/run/pipes/saveCode.pipe.ts, backEnd/api/src/run/run.controller.ts, backEnd/api/src/run/run.service.ts, backEnd/running/src/codes/codes.controller.ts, backEnd/running/src/codes/codes.service.ts, backEnd/running/src/codes/dto/request-code.dto.ts, backEnd/running/src/codes/dto/response-code.dto .ts, backEnd/running/src/common/type.ts, backEnd/running/src/common/utils.ts, backEnd/running/src/mq/dto/response-codeblock.dto.ts, backEnd/running/src/mq/mq.consumer.ts
다른 언어를 지원하기 위해서 기존 코드 수정
- 코드 수정이 일어난 기능 : 코드 저장, 실행
아직 Javascript 언어에 대한 에러 메세지 파싱, 보안 검사 로직은 추가되지 않았습니다.
그래서 javascipt 코드에서 에러가 발생하는 요청을 보내면 항상 알 수 없는 에러가 발생하는 상태입니다.
지원하는 언어를 문자 리터럴 타입으로 정의해서 검증합니다.
```javascipt
export type supportLang = 'python' | 'javascript';
```
자식 프로세스로 파일 실행 후 에러를 처리하는 과정에서 한 함수 내부에서 에러를 검증하고 다시 던지고 캐치하는 코드를 줄이는 방향으로 리팩토링을 진행했습니다.
```
fs.writeFileSync(filePath, code);
const { stdout, stderr } = await this.runCommand(filePath, language);
if (stderr) {
if (stderr === Messages.UNKNOWN) {
throw new InternalServerErrorException();
}
const errorMessage = this.getErrorMessage(stderr);
throw new RunningException(errorMessage);
}
fs.unlinkSync(filePath);
return this.getOutput(stdout);
```
자식프로세스로 실행한 것에대한 에러는 실제 node 에러가 발생하지 않고 stderr에 담기므로 따로 처리해주지 않아도 되었고,
그 이외에 fs …
=> [BE] feature: 다른 언어 지원 기능 구현 - 코드 저장 및 실행

backEnd/api/src/common/utils.ts, backEnd/api/src/run/run.controller.ts, backEnd/api/src/run/run.gateway.ts, backEnd/api/src/run/run.service.ts
- 코드 실행 요청 v3 변경 - 소켓만 이용하는 방식으로
[WebSocket을 이용한 코드 실행 요청 처리](https://energetic-palm-634.notion.site/WebSocket-3b9601b4b6d64c05a0984fcf05ba5e2e?pvs=4)
=>  [BE] feature : 코드 실행 요청 v3 - 소켓만 이용

frontEnd/src/configs/highlightCodeConfig.ts, frontEnd/src/utils/highlightCode.ts
- 번들링 크기를 줄이기 위해 highlight.js에서 사용하는 언어만 import 하도록 수정
- [📦 번들링 크기 줄이기](https://github.com/boostcampwm2023/web05-AlgoITNi/wiki/%F0%9F%93%A6-%EB%B2%88%EB%93%A4%EB%A7%81-%ED%81%AC%EA%B8%B0-%EC%A4%84%EC%9D%B4%EA%B8%B0)
=> [FE] refactor: highlight.js 사용하는 언어만 import 하도록 수정

frontEnd/src/components/modal/Modals.tsx, frontEnd/src/components/room/QuizViewSection.tsx, frontEnd/src/hooks/useModal.ts, frontEnd/src/stores/useModalState.ts, frontEnd/vite.config.ts
QuizSection, ControllSection, Modal 렌더링 최적화
- #173 
https://github.com/boostcampwm2023/web05-AlgoITNi/assets/99241871/965c0d44-f464-47d4-b9ab-fa1a0d23a2b6
https://github.com/boostcampwm2023/web05-AlgoITNi/assets/99241871/6fd39b02-41af-4646-811c-0c29a3d88b38
Zustand의 전역상태인 useModalState를 사용하는 컴포넌트의 경우, modals 배열이 변경되면 전부 리렌더링되는 문제가 있었다.
이런 문제를 해결하기위해 Zustand의 state배열에 actions라는 객체를 만들고, 이걸 사용했다.
actions의 주소값은 변하지 않기 때문에 렌더링 문제가 해결되었다.
QuizSection의 경우, Room이 리렌더되어도(stream이 변하는경우) 다시 리렌더될 필요가 없다.
그래서 React.memo를 통해 메모이제이션을 해주었다.
=> [FE] feat: QuizSection, ControllSection, Modal 렌더링 최적화

backEnd/api/.gitignore, backEnd/api/package-lock.json, backEnd/api/package.json, backEnd/api/src/codes/codes.service.ts, backEnd/api/src/common/decorator/typeormTransactional.decorator.ts, backEnd/api/src/run/run.gateway.ts, backEnd/api/src/run/run.service.ts, backEnd/api/src/users/users.service.ts, backEnd/api/test/loadtest.js, backEnd/api/test/v1-stress.yml, backEnd/api/test/v2-stress.yml, backEnd/api/test/v3-stress.yml, backEnd/running/Dockerfile, backEnd/running/package-lock.json, backEnd/running/package.json, backEnd/running/src/codes/codes.service.ts, backEnd/running/src/mq/mq.consumer.ts
- transaction 적용 및 에러 fix
- 쓰기 작업이 일어나는 경우만 transaction을 추가해주었습니다.
- 코드 실행 시 임시 파일 생성 이름 : Date.now() - > uuid로 변경 , 여러 프로세스에서 동시 실행시 같은 이름에 파일이 생성, 삭제되어 오류남
- 현재는 트랜잭션 코드 AOP 처리가 되어있지 않으나, 추후 service 레벨에 적용할 수 있는 트랜잭션 데코레이터를 생성해서 적용하는 것이 목표입니다.
: AsyncLocalStorage 또는 cls-hooked 를 이용해서 http 요청 당 전역으로 이용할 수 있는 namespace를 만들어 쿼리러너를 이용하고 싶음.
: 실패시 대안 1. controller 레벨에서 인터셉터, 데코레이터 활용. 2. 이미 만들어져있는 패키지 이용
=> [BE] feature : transaction 적용 및 에러 fix

frontEnd/src/apis/postRunCode.ts, frontEnd/src/components/room/EditorSection.tsx, frontEnd/src/components/room/editor/EditorButton.tsx, frontEnd/src/components/room/editor/LoadButton.tsx, frontEnd/src/components/room/editor/SaveButton.tsx
- 코드 실행 소켓 방식으로 변경
- 소켓 방식으로 변경되면서 이벤트가 순차적으로 일어나야 했음
- 소켓 연결 -> 코드 실행 요청 이벤트 발생 -> (코드 실행) -> 결과 반환 이벤트 발생 -> 소켓 연결 종료
- 이를 위해 각 이벤트가 순서대로 일어날 수 있도록 구성
```ts
const handleExecCode = () => {
executionSocket = io(VITE_CODE_RUNNING_SOCKET_URL, { transports: ['websocket'] });
executionSocket.on('done', (response: RunCodeResponse) => {
setExecResult(getOutputString(response));
setIsExec(false);
executionSocket.disconnect();
});
executionSocket.on('connect', () => {
setIsExec(true);
setExecResult('');
executionSocket.emit('request', { code: plainCode, language: languageName });
});
};
```
=> [FE] fix: 코드 실행 소켓 방식으로 변경

frontEnd/src/components/room/ChattingSection.tsx, frontEnd/src/components/setting/MediaSelector.tsx, frontEnd/src/components/setting/Settings.tsx, frontEnd/src/pages/Room.tsx, frontEnd/src/stores/useRoomConfigData.ts
roomConfigData 전역 state로 관리
Room에서 nickname과 setting을 props로 계속해서 넘겨주어 가독성이 나빠지는 부분을 개선하였습니다!
nickname과 setting관련 상태와 함수를 useRoomConfigData로 관리하였습니다.
=> [FE] refactor: roomConfigData 전역 state로 관리

frontEnd/src/components/room/editor/Editor.tsx, frontEnd/src/components/room/editor/InputArea.tsx
한국어 crdt 구현
- 한국어 crdt 구현
기존의 문제점은 한글이 한글자씩 입력되는 경우 ytext에 자모음이 하나씩 입력되어 한글이 깨진다는 것이었다.
이를 해결하기 위해 compositionEnd 이벤트를 사용했다. 
한글이 완성되었을 때 발생하는 이벤트인데, 이때  ytext에 추가시키는 형태로 구현했다.
또한, 기존의 onChange함수에서 한 글자에 한글인 경우에 대해서는 ytext에 처리하지 않는 형태로 구현하여 해결했다.
```typescript
const handleChange = (event: React.ChangeEvent<HTMLTextAreaElement>) => {
const newText = event.target.value;
const newCursor = event.target.selectionStart; // 연산 이후의 최종 위치
setPlainCode(newText);
setCursorPosition(newCursor);
const changedLength = plainCode.length - newText.length;
const isAdded = changedLength < 0;
if (isAdded) {
const addedText = newText.slice(newCursor - Math.abs(changedLength), newCursor);
const isOneLetter = addedText.length === 1;
const isKorean = addedText.match(/[ㄱ-ㅎ|ㅏ-ㅣ|가-힣]/);
if (isOneLetter && isKorean) …
```
=> [FE] feat: 한국어 crdt 구현

frontEnd/src/components/room/ChattingSection.tsx, frontEnd/src/hooks/tests/useInput.test.ts, frontEnd/src/hooks/useInput.ts, frontEnd/src/hooks/useLastMessageViewingState.ts, frontEnd/src/hooks/useScroll.ts
Chatting Section의 코드를 읽기 좋게 개선
1. useInput을 더 범용성 있게 사용할 수 있도록 reset함수를 추가하여 값을 초기화시킬 수 있도록 변경했고, 해당 부분에 대한 테스트함수를 추가했다.
2. 기존에 ChattingSection에 있던 로직부분을 hook으로 분리하고, 각 훅을 재사용할 수 있도록 작성했다.
=> [FE] refactor: Chatting Section 리팩토링

frontEnd/src/components/room/modal/LoginModal.tsx, frontEnd/src/pages/Room.tsx
로그인 리다이렉트시 방설정 창이 보이는 오류 해결
- 로그인 리다이렉트시 방설정 창이 보이는 오류 해결
기존의 isSettingDone이 그 역할을 했으나, 현재 isSettingDone는 signal을 시작시키는 트리거형태로 작동하기 때문에, 로그인시의 redirection인지, 첫 접속인지 분기할 필요가 있었다.
hasLogin이라는 변수를 하나 선언하고이전에 저장된 code와 nickName값에 따라 로그인 리다이렉션인지, 처음 접속하는 과정인지를 분기할 수 있도록 했다.
```typescript
const defaultCode = localStorage.getItem('code');
const defaultNickName = localStorage.getItem('nickName');
const hasLogin = (!!defaultCode || defaultCode === '') && !!defaultNickName;
export default function Room() {
if (!isConnectionDone && !hasLogin) return <Setting mediaObject={mediaObject} />;
...
}
```
=> [FE] fix: 로그인 리다이렉트시 방설정 창이 보이는 오류 해결

frontEnd/src/components/common/ChattingErrorToast.tsx, frontEnd/src/components/room/ChattingSection.tsx, frontEnd/src/components/room/chatting/ChattingInput.tsx, frontEnd/src/components/room/chatting/ChattingMessage.tsx, frontEnd/src/hooks/useInput.ts
- 채팅 영역 리팩토링
- close #217 
- 입력에 의해 메시지 영역의 모든 메시지가 재렌더링 되는 문제 발생
- 기존에는 state를 최상위 컴포넌트인 ChattingSection이 가지고 있었기 때문에 발생한 문제
- 이를 해결하기 위해 가능한 많은 state를 최하위 컴포넌트가 갖고 있을 수 있도록 수정
- state의 변경 영향을 최소화 시키기 위함
- React memo 기능을 이용하여 한 번 렌더링 된 메시지가 재렌더링 되는 것을 방지
=> [FE] refactor: 채팅 영역 리팩토링

backEnd/chat/src/chat/chat.gateway.spec.ts, backEnd/chat/src/chat/chat.gateway.ts, backEnd/chat/src/commons/utils.ts
- redis 채널 구독 방식 수정
- 기존 방 이름으로 채널을 구독하는 방식에서 Chatting 채널 구독 방식으로 수정
- room 이름이 아닌 Chatting 채널 구독 방식 사용
=> fix: [BE] redis 채널 구독 방식 수정

frontEnd/src/components/room/QuizViewSection.tsx, frontEnd/src/components/room/chatting/ChattingInput.tsx, frontEnd/src/components/room/quizView/ClickToQuizInput.tsx, frontEnd/src/components/room/quizView/ErrorView.tsx
채팅, 문제보기 오류 처리
https://github.com/boostcampwm2023/web05-AlgoITNi/assets/99241871/dbacb2da-a4fb-469c-a9dc-742617daec81
https://github.com/boostcampwm2023/web05-AlgoITNi/assets/99241871/4e93811d-80fd-4b39-8e4d-1119b5201578
=> [FE] feat: 채팅, 문제보기 오류 처리

frontEnd/src/components/common/RouterSpinner.tsx, frontEnd/src/main.tsx, frontEnd/src/pages/Room.tsx
- 라우팅 로딩 스피너 추가
https://github.com/boostcampwm2023/web05-AlgoITNi/assets/99241871/a66e86c4-449c-4da2-86a9-de3d3f1589d8
crdt와 Modal이 home화면에서 로드되는 문제가 있었는데, main.tsx에서 Room.tsx 내부로 옮겨 동적 import될 수 있도록 처리했다.
또한, 동적으로 파일을 가져오는동안 보여줄 로딩 스피너를 추가했다.
=> refactor: [FE] 라우팅 로딩 스피너 추가

backEnd/running/src/codes/codes.service.ts, backEnd/running/src/common/supportLang.ts
- 컴파일이 필요한 언어 코드 실행 fix
c, swift, kotlin의 경우  cli로 언어를 실행시킬때 두 번의 명령어 입력이 필요함.
exec에서 spawn으로 변경하면서 자식프로세스 생성시 커맨드 전달방식 변경되었음
[기존]
`gcc -o target target.c && target`으로 명령어 실행
[변경]
`gcc -o target target.c`
`target`
두 단계로 나누고, 자식프로세스를 두 번 생성
=> [BE] fix: 컴파일이 필요한 언어 코드 실행 fix

frontEnd/src/apis/getSocketURL.ts, frontEnd/src/components/room/ChattingSection.tsx, frontEnd/src/hooks/useRTCConnection.ts, frontEnd/src/utils/createSocket.ts
=> [FE] feat: 소켓 연결방식 변경

README.md, backEnd/api/src/auth/auth.controller.ts, backEnd/api/src/common/transaction/transaction.service.ts, backEnd/api/src/users/users.service.ts, backEnd/running/src/codes/codes.service.ts
- 회원가입 트랜잭션 범위 수정
- 코틀린 타임아웃 메시지 미출력 수정
코틀린 코드가 타임아웃으로 종료될 때 메시지가 출력되지 않는 오류가 존재했음
-> 다른언어는 종료 시그널 `SIGINT`로 프로세스가 종료되었는데 코틀린은 종료코드 `130`으로 종료됨
SIGINT와 130은 동일한 POSIX 시그널!
따라서 이 프로세스가 어떤 시그널로 종료되었는지 체크하는 부분에 시그널과 코드 두 가지 모두 체크하게 함
=> [BE] fix: 회원가입 트랜잭션 범위 수정 & 타임아웃 시그널 수정

README.md, backEnd/api/src/common/logger/winstonLogger.service.ts, backEnd/running/src/codes/codes.service.ts, backEnd/running/src/common/logger/winstonLogger.service.ts, backEnd/running/src/common/supportLang.ts
코드 실행기능 리팩터링 및 README.md 수정
- README.md
데모영상 링크추가
이미지 파일 사이즈 줄임
이미지 표로 감싸기
- 코드 실행기능
java, kotlin 한글 출력 인코딩 오류 fix
타임아웃 리팩터링
- child_process 생성 옵션에 timeout 옵션이 있어 해당 방식으로 수정
=> refactor: [BE] 코드 실행기능 리팩터링 및 README.md 수정
