boostcampwm2023/web05-AlgoITNi

frontEnd/.eslintrc.cjs
frontEnd/.gitignore
frontEnd/.prettierrc
frontEnd/README.md
frontEnd/index.html
frontEnd/jest.config.ts
frontEnd/jest.setup.ts
frontEnd/package-lock.json
frontEnd/package.json
frontEnd/postcss.config.js
frontEnd/src/main.tsx
frontEnd/src/pages/Home.tsx
frontEnd/src/pages/Room.tsx
frontEnd/src/pages/tests/Home.test.tsx
frontEnd/src/styles/font.css
frontEnd/src/styles/index.css
frontEnd/src/vite-env.d.ts
frontEnd/tailwind.config.js
frontEnd/tsconfig.json
frontEnd/tsconfig.node.json
frontEnd/vite.config.ts

FrontEnd 초기환경설정입니다.
- react 설정
- react routing 설정
- prettier설정
- lint 기본 설정
- jest 테스팅 환경 설정
- tailwind 설치

frontend 초기환경설정

---

backEnd/api/src/app.module.ts
backEnd/api/src/decorator/query-runner.decorator.ts
backEnd/api/src/interceptor/timeout.intercetor.ts
backEnd/api/src/interceptor/transaction.intercetor.ts
backEnd/api/src/logger/logger.middleware.spec.ts
backEnd/api/src/logger/logger.middleware.ts
backEnd/api/src/main.ts
backEnd/api/src/utils.ts
backEnd/running/src/app.module.ts
backEnd/running/src/interceptor/timeout.intercetor.ts
backEnd/running/src/logger/logger.middleware.spec.ts
backEnd/running/src/logger/logger.middleware.ts
backEnd/running/src/main.ts

---
name: Feature request
about: 기능 추가 템플릿입니다.
title: '초기 필요 인터셉터 및 미들웨어 추가'
labels: 'feature'
assignees: 'Gseungmin'
---
Nest.js 개발에 들어가기 전 필요한 인터셉터 및 미들웨어 추가
* 인터셉터를 통해 요청 처리 후, 커밋 또는 롤백을 진행
* 또한 쿼리러너를 요청에 삽입하여 핸들러에서 처리할 수 있게 구현
* 인터셉터를 통해 요청 처리 후에 처리 시간 슬랙에 전송
* 슬랙에 전송한 이유는 추후 처리 시간이 긴 요청에 대해서만 메시지를 전송하기 위한 확장성을 고려

Nest 개발 전 인터셉터 및 미들웨어 셋팅

---

.github/workflows/front-release-deploy.yml

프론트엔드 FE/release브랜치 풀리퀘스트에 대한 CI/CD로직 구성
⇒ N Cloud Object Storage를 사용한 Web Server 구성
정적파일 웹사이트 호스팅을 사용해서 구성
현재 우리 프로젝트에서는 서버컴포넌트(SSR)이 필요한 부분이 없고, 클라이언트단의 기능으로 구성이된다.
따라서 서버 렌더링이 필요하지 않기에 빌드된 html, css, js를 Object Stroage에 공개형태로 배포해서 도메인으로 접근할 수 있게 했다.
배포 테스트
N Cloud Object Storage는 aws API와 호환이 된다. 따라서 aws cli를 사용해서 업로드 해보았다.
**AWS 키정보 설정**
```bash
aws configure
AWS Access Key ID [None]: NCloud-Access-Key
AWS Secret Access Key [None]: NCloud-Secret-Access-Key
Default region name [None]:
Default output format [None]:
```
**S3 api 활용하여 빌드파일 업로드**
```bash
aws --endpoint-url=https://kr.object.ncloudstorage.com s3 cp --recursive dist s3://algoitni
```
workflows에 yml을 작성하여 특정 브랜치에 작업이 일어날 때 작성한 yml을 기반으로 action일 일어나게 했다.

[FE] feat: 프론트엔드 FE/release브랜치 풀리퀘스트에 대한 CI/CD로직 구성

---

.github/workflows/front-release-deploy.yml

[FE] fix: yml 경로 수정

---

.github/workflows/front-release-deploy.yml

npm install run 대신 uses를 사용해서 발생한 오류 해결

[FE] fix: npm install run 대신 uses를 사용해서 발생한 오류 해결

---

.github/workflows/front-release-deploy.yml

npm install에서 run대신 uses를 사용해서 발생한 오류 해결

[FE] fix: npm install에서 run대신 uses를 사용해서 발생한 오류 해결

---

.github/workflows/front-release-deploy.yml

aws default 리전 추가하여 코드가 업로드되지 않던 오류 해결

[FE] fix: aws 리전 추가하여 코드가 업로드되지 않던 오류 해결

---

.github/workflows/back-release-deploy.yml
backEnd/api/DockerFile
backEnd/api/deploy.sh

[BE] CI/CD 스크립트 작성

---

backEnd/signaling/src/app.module.ts
backEnd/signaling/src/main.ts

fix: [BE] 소켓 통신 오류 수정

---

.github/workflows/front-release-deploy.yml

cloudFront 캐시 무효화시 env가 설정되지 않아 제대로 배포되지 않던 문제 해결

[FE] fix: 프론트엔드 deploy 키 설정

---

.github/workflows/front-ci.yml
.github/workflows/front-release-deploy.yml

[FE] 프론트엔드 배포 오류 해결

---

.github/workflows/front-ci.yml
.github/workflows/front-release-deploy.yml

[FE] chore: 빌드시 .env설정

---

.github/workflows/back-api-cd.yml
.github/workflows/back-api-ci.yml

ci/cd 가 한 파일에 적용되어 테스트 상황에서도 배포되던 문제 수정
- github action ci/cd 파일 분리

[BE] fix: github action ci/cd 분리

---

.github/workflows/back-api-cd.yml
.github/workflows/back-api-ci.yml

- nest g로 모듈 생성 시 test 코드가 자동 생성되나 유효하지 않은 내용
테스트 코드는 아직 작성하지 않았으므로 ci에서 test를 생략

[BE] fix : cicd 과정 중 문제 수정

---

.github/workflows/front-ci.yml
.github/workflows/front-release-deploy.yml
frontEnd/src/hooks/useRoom.ts

[FE] fix: STUN/TURN 실제 서버 연결

---

backEnd/chat/.eslintrc.js
backEnd/chat/.gitignore
backEnd/chat/.prettierrc
backEnd/chat/Dockerfile
backEnd/chat/README.md
backEnd/chat/nest-cli.json
backEnd/chat/package-lock.json
backEnd/chat/package.json
backEnd/chat/src/app.controller.spec.ts
backEnd/chat/src/app.controller.ts
backEnd/chat/src/app.module.ts
backEnd/chat/src/app.service.ts
backEnd/chat/src/chat/chat.gateway.ts
backEnd/chat/src/chat/chat.service.spec.ts
backEnd/chat/src/chat/chat.service.ts
backEnd/chat/src/chat/dto/join-room.dto.ts
backEnd/chat/src/chat/dto/leave-room.dto.ts
backEnd/chat/src/chat/dto/message.dto.ts
backEnd/chat/src/commons/utils.ts
backEnd/chat/src/main.ts
backEnd/chat/test/app.e2e-spec.ts
backEnd/chat/test/jest-e2e.json
backEnd/chat/tsconfig.build.json
backEnd/chat/tsconfig.json

- PUB/SUB 구조를 통해 멀티 클러스팅 소켓 통신 구현
[PUB/SUB 다중소켓](https://velog.io/@jism0211/%EB%8B%A4%EC%A4%91-%EC%86%8C%EC%BC%93-%EA%B4%80%EB%A6%AC%ED%95%98%EA%B8%B02-PUBSUB)
* 문제는 같은 이름의 Room에 join 하더라고, 다른 소켓에 있으면 통신할 수 없음
* 이 문제를 해결하기 위해 PUB/SUB 구조 활용
* Room 이름이르 PUB/SUB 구조를 활용하면 서로 다른 소켓에 있더라도, 같은 이름의 ROOM에 JOIN해 있다면 통신이 가능

[BE]: 멀티 클러스터링 채팅 소켓 통신 구현

---

.github/workflows/back-center-cd.yml
.github/workflows/back-center-ci.yml
.github/workflows/back-chat-cd.yml
.github/workflows/back-chat-ci.yml
.github/workflows/back-signaling-cd.yml

- actinos 파일 생성 및 수정
- center 서버 actions 설정
- chat 서버 actions 설정
- signaling 서버 actions 설정
- running 서버 actions 설정

[BE] 백엔드 C0I/CD 설정

---

.github/workflows/back-center-cd.yml
.github/workflows/back-center-ci.yml
.github/workflows/back-chat-cd.yml
.github/workflows/back-chat-ci.yml
.github/workflows/back-running-cd.yml
.github/workflows/back-signaling-cd.yml
.github/workflows/back-signaling-ci.yml

fix: [BE] 스크립트 연산자 수정 > -> >>

---

.github/workflows/back-center-cd.yml
.github/workflows/back-center-ci.yml
.github/workflows/back-chat-cd.yml
.github/workflows/back-chat-ci.yml
.github/workflows/back-running-cd.yml
.github/workflows/back-signaling-cd.yml
.github/workflows/back-signaling-ci.yml

release: [BE] 백엔드 배포 수정

---

frontEnd/src/hooks/useMedia.ts
frontEnd/src/hooks/useRTCConnection.ts
frontEnd/src/pages/Room.tsx
frontEnd/src/pages/tests/Room.test.tsx

소켓 연결 방식을 fetching후에 연결하는 형태로 변경 하였습니다.
또한 stream 관련 오류를 해결하였습니다.
https://github.com/boostcampwm2023/web05-AlgoITNi/assets/99241871/ac0db054-a506-4ca0-9598-a0d3782e6710
socket의 연결 url이 center 서버를 통해 얻어지는식으로 변경되어 fetch를 통해 url을 받아오고, 이를 통해 연결하도록 변경했다.
```typescript
useEffect(() => {
navigator.mediaDevices
.getUserMedia({
video: selectedCamera ? { deviceId: { exact: selectedCamera } } : true,
audio: selectedMic ? { deviceId: { exact: selectedMic } } : true,
})
.then((stream) => {
setUserStream(stream);
});
navigator.mediaDevices.enumerateDevices().then((res) => {
setCameraList(res.filter((mediaDevice) => mediaDevice.kind === 'videoinput'));
setMicList(res.filter((mediaDevice) => mediaDevice.kind === 'audioinput'));
setSpeakerList(res.filter((mediaDevice) => mediaDevice.kind === …
```

[FE] fix: 소켓 연결 방식 변경, stream 관련 오류 해결

---

backEnd/api/src/auth/auth.controller.ts
backEnd/api/src/users/users.service.ts

fix: [BE] DB 비동기 순서 에러 수정

---

frontEnd/src/components/common/Modal.tsx
frontEnd/src/hooks/useFocus.ts

모달이 띄워진 상태에서 esc를 누르면 꺼지는 기능 추가
자동 focus를 해주는 ref를 반환하는 useFocus훅을 만들어 로직을 간소화시켰다.

[FE] feat: 모달이 띄워진 상태에서 esc를 누르면 꺼지는 기능 추가

---

backEnd/api/package-lock.json

[BE] package 및 package-lock.json 버전 문제 수정

---

.github/workflows/back-api-cd.yml
backEnd/api/src/app.module.ts

[BE] 마스터 DB 슬레이브 DB 적용

---

frontEnd/src/components/room/editor/LoadButton.tsx
frontEnd/src/components/room/modal/CodeListModal.tsx
frontEnd/src/components/room/modal/WarningCodeLoadModal.tsx

[FE] 코드 로드시 경고창 추가

---

frontEnd/src/apis/putUserCode.ts

[FE] fix: api 오타 수정

---

backEnd/api/.gitignore
backEnd/api/src/run/run.gateway.ts
backEnd/api/src/run/run.service.ts
backEnd/api/test.js
backEnd/running/src/codes/codes.service.ts
backEnd/running/src/codes/errorMessage.ts

javascript 보안검사, 에러메세지 처리 기능 추가

[BE] feature : javascript 보안검사, 에러메세지 처리 기능 추가

---

frontEnd/src/apis/postUserCode.ts
frontEnd/src/components/room/EditorSection.tsx
frontEnd/src/components/room/editor/LoadButton.tsx
frontEnd/src/components/room/editor/SaveButton.tsx
frontEnd/src/components/room/modal/CodeListModal.tsx
frontEnd/src/components/room/modal/SaveChoiceModal.tsx
frontEnd/src/components/room/modal/SaveModal.tsx
frontEnd/src/components/room/modal/tests/SaveModal.test.tsx
frontEnd/src/types/editor.ts
frontEnd/src/types/loadCodeData.ts
frontEnd/src/utils/file.ts
frontEnd/vite.config.ts

코드 불러오기, 저장, 수정시 제목과 언어 타입도 변경하도록 처리

[FE] 코드 불러오기, 저장, 수정시 제목과 언어타입도 변경하도록 처리

---

frontEnd/src/components/room/chatting/ChattingMessage.tsx

[FE] fix: 내가 보낸 채팅에 내 닉네임이 표시되도록 변경

---

frontEnd/src/components/common/Button.tsx
frontEnd/src/components/room/editor/EditorButton.tsx
frontEnd/src/components/room/editor/LoadButton.tsx
frontEnd/src/components/room/editor/SaveButton.tsx
frontEnd/src/utils/file.ts

[FE] feat: UI 버튼 수정 & 로컬 다운로드 버튼 오류 해결

---

frontEnd/src/components/room/VideoSection.tsx
frontEnd/src/pages/Room.tsx

[FE] fix: 에디터 높이 수정

---

frontEnd/src/components/room/VideoSection.tsx
frontEnd/src/components/room/video/MyVideo.tsx
frontEnd/src/components/room/video/OtherVideos.tsx
frontEnd/src/components/setting/EmptyVideo.tsx
frontEnd/src/components/setting/MicControlButton.tsx
frontEnd/src/components/setting/SettingVideo.tsx
frontEnd/src/components/setting/VideoControlButton.tsx

[FE] fix: 비디오 권한이 없는 경우 검은 화면으로 처리

---

frontEnd/src/components/room/EditorSection.tsx
frontEnd/src/components/room/editor/Editor.tsx
frontEnd/src/components/room/editor/LoadButton.tsx
frontEnd/src/contexts/crdt.tsx
frontEnd/src/hooks/useDataChannelOnMessage.ts

- Yjs CRDT 추가
- #54 
- Yjs 사용 방법에 대한 자료가 많이 없었음
- 저번 주에 CRDT를 직접 구현하는 과정이 Yjs의 기능들을 이해하는데 도움이 되었음

[FE] feat: Yjs CRDT 추가

---

backEnd/api/Dockerfile
backEnd/api/package-lock.json
backEnd/api/package.json
backEnd/api/src/codes/dto/getCode.dto.ts
backEnd/api/src/codes/dto/saveCode.dto.ts
backEnd/api/src/codes/pipes/saveCode.pipe.ts
backEnd/api/src/codes/schemas/code.schemas.ts
backEnd/api/src/common/logger/winstonLogger.service.ts
backEnd/api/src/common/supportLang.ts
backEnd/api/src/common/type.ts
backEnd/api/src/common/utils.ts
backEnd/api/src/mq/mq.module.ts
backEnd/api/src/mq/mq.service.ts
backEnd/api/src/run/dto/request-codeblock.dto.ts
backEnd/api/src/run/pipes/saveCode.pipe.ts
backEnd/api/src/run/run.controller.ts
backEnd/api/src/run/run.gateway.ts
backEnd/api/src/run/run.module.ts
backEnd/api/src/run/run.service.ts
backEnd/api/test/v1-stress.yml
backEnd/api/test/v2-stress.yml
backEnd/api/test/v3-stress.yml
backEnd/running/.gitignore
backEnd/running/Dockerfile
backEnd/running/src/codes/codes.controller.ts
backEnd/running/src/codes/codes.service.ts
backEnd/running/src/common/logger/winstonLogger.service.ts
backEnd/running/src/common/type.ts
backEnd/running/src/common/utils.ts
backEnd/running/src/mq/mq.consumer.ts

- 부하테스트 후 코드 개선, 언어 지원 확대
- 소켓 정보 저장 후 해제 안되는 경우 -> 크론으로 매 분마다 찾아 10초 이상 연결된 소켓 해제
- 이벤트 에미터 방식 제거 -> 이벤트 에미터 방식이 불필요한 과정으로 판단되어 제거
- 보안 검사 로직 변경 
-  기존 api 서버에서 보안 검사하던 것은 언어 확장성이 좋지 않아 제거
- 대신 running 서버에서 사용자 권한 제한을 통해서 보안 강화
- 모든 로그가 한 파일에 저장되어 에러 로그만 보기 어려웠음
- 부하 테스트시 발생한 에러에 대한 로그가 찾기 힘듦
- 에러로그만 별로도 저장하는 winston transport를 추가해 에러로그만 찾아볼 수 있게 개선

[BE] feature, refactor : 부하테스트 후 코드 개선, 언어 지원 확대

---

frontEnd/src/components/room/ChattingSection.tsx

- 채팅 소켓 에러 핸들링 수정
- (너무 빨라서 못찍음)

fix: [FE] 채팅 소켓 에러 핸들링 수정

---

frontEnd/src/configs/highlightCodeConfig.ts
frontEnd/src/constants/editor.ts
frontEnd/src/types/editor.ts

feat: [FE] 코드 실행 JAVA, C 추가

---

backEnd/api/src/common/supportLang.ts
backEnd/api/src/run/run.gateway.ts
backEnd/running/Dockerfile
backEnd/running/src/codes/codes.service.ts
backEnd/running/src/codes/dto/request-code.dto.ts
backEnd/running/src/common/supportLang.ts
backEnd/running/src/common/type.ts
backEnd/running/src/common/utils.ts

- swift, kotlin 지원
- 도커 환경설정
- api 서버 지원
- running 서버 지원
언어 환경이 모두 설정되어있는 도커파일을 미리 만들어 허브에 올려둔 후 bulid시 Base 이미지로 활용

[BE] feature : swift, kotlin 지원

---

backEnd/api/src/run/run.gateway.ts
backEnd/running/Dockerfile

[BE] fix:  running 서버 실행 옵션 수정

---

frontEnd/src/components/setting/UserInputArea.tsx
frontEnd/src/hooks/useMedia.ts
frontEnd/src/stores/useRoomConfigData.ts

카메라 권한을 받지 못하는 경우 처리
useRoomConfigData에 mediaPermission상태를 추가하고, useMedia에서 promise가 reject되면 상태를 false로 변경시키도록 처리했다.

[FE] feat: 카메라 권한을 받지 못하는 경우 처리

---

frontEnd/src/components/room/VideoSection.tsx
frontEnd/src/components/room/editor/EditorButton.tsx
frontEnd/src/components/room/editor/LoadButton.tsx
frontEnd/src/components/room/editor/SaveButton.tsx
frontEnd/src/components/room/video/MyVideo.tsx
frontEnd/src/components/room/video/OtherVideos.tsx
frontEnd/src/pages/Room.tsx

feat: [FE] Room 반응형 추가

---

frontEnd/src/components/room/chatting/ChattingInput.tsx

[FE] fix: 채팅 한글 입력 두 번 전송되는 문제 해결

---

backEnd/api/src/crawler/crawler.controller.ts

Nginx 캐싱 기능 컨트롤러 추가

---

frontEnd/index.html
frontEnd/src/pages/Home.tsx

[FE] refactor: 이미지 preload 설정

---

frontEnd/src/components/room/modal/LoginModal.tsx

[FE] fix: 로그인 리다이렉트 세미콜론 제거

---

README.md

- README.md 수정
- 구성 순서
- 기술 스택 뱃지에 버전 넣을지?
https://github.com/HKLeeeee/web05-AlgoITNi/tree/BE126/feature/readme

chore: README.md 수정

---

backEnd/center/src/connections/connections.controller.ts

fix: [BE] HTTP 메서드 수정

---

frontEnd/src/components/room/EditorSection.tsx
frontEnd/src/components/room/editor/Editor.tsx
frontEnd/src/components/room/editor/InputArea.tsx
frontEnd/src/components/room/editor/LoadButton.tsx
frontEnd/src/components/room/modal/CodeListModal.tsx
frontEnd/src/contexts/crdt.tsx
frontEnd/src/services/crdt.ts

crdt yjs interface 의존성 주입을 통한 결합도 낮추기

[FE] refactor: crdt yjs interface 의존성 주입을 통한 결합도 낮추기

---

README.md
backEnd/api/src/common/logger/winstonLogger.service.ts
backEnd/running/src/codes/codes.service.ts
backEnd/running/src/common/logger/winstonLogger.service.ts
backEnd/running/src/common/supportLang.ts

Reverts boostcampwm2023/web05-AlgoITNi#262

Revert "refactor: [BE] 코드 실행기능 리팩터링 및 README.md 수정"
